name: Save iregs as text

on:
  workflow_dispatch:
  schedule:
    - cron: '2 8 * * 1'

env:
  PARTS: "1004,1006"

jobs:
  save-iregs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installs htmlq
        uses: baptiste0928/cargo-install@v3.0.0
        with:
          crate: htmlq
          version: "0.4.0"

      - name: Fetch and extract parts from iRegs
        run: |
          IFS="," read -a BASH_PARTS <<< "$PARTS"
          for PART in "${BASH_PARTS[@]}"; do
            echo "$PART"
            CHUNKS=($(curl -sSL "https://www.consumerfinance.gov/rules-policy/regulations/${PART}/" |
              htmlq -t '.o-secondary-nav_link' -a href -b 'https://www.consumerfinance.gov'
            ))
            for CHUNK in "${CHUNKS[@]}"; do
              echo "$CHUNK"
            done
            echo "${CHUNKS[*]}"
            curl -sSL "${CHUNKS[*]}" |
              htmlq -r '.regulation-meta, .inline-interpretation, .block__sub' |
              htmlq -t '.u-layout-grid_main' |
              sed '/^ *$/d' |
              awk '{$1=$1};1' > "./iregs/${PART}.txt"
          done

      - name:  Test
        run: |
          ls -l iregs
          cat iregs/1004.txt
          #- name: Commit text
          #uses: stefanzweifel/git-auto-commit-action@v5.0.0
          #with:
          #commit_message: Nightly update
